Repository brave/security-action, pull requests merged in 2024-03, with the labels that each got.

#526 github workflows: spread jobs to not incur in RL
  .github/workflows/add-maintainer-custom-property.yml
  .github/workflows/renovate-sanity-check.yml
Labels: unverified-commits

#531 semgrep rules: March 2024 Update
  assets/semgrep_rules/generated/nonfree/audit.yaml
  assets/semgrep_rules/generated/nonfree/others.yaml
  assets/semgrep_rules/generated/nonfree/vulns.yaml
  assets/semgrep_rules/generated/oss/audit.yaml
  assets/semgrep_rules/generated/oss/vulns.yaml
  assets/semgrep_rules/update-ruleset.rb
Labels: puLL-Merge

#540 Add Android Resolve Intent rule
  assets/semgrep_rules/client/android-resolve-intent.java
  assets/semgrep_rules/client/android-resolve-intent.kt
  assets/semgrep_rules/client/android-resolve-intent.yaml
Labels: needs-security-review

#546 action.yml: remove auth hotword
  action.yml
Labels: needs-security-review

#553 pip-audit: Support pyproject.toml [project].dependencies
  action.yml
  assets/pip-audit.py
  t3sts/pipaudit/pyproject.toml
Labels: needs-security-review

#556 Add iOS Javascript injection rules
  assets/semgrep_rules/client/brave-execute-script-ios.swift
  assets/semgrep_rules/client/brave-execute-script-ios.yaml
Labels: needs-security-review
